name: Build and Deploy

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master
      
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        # ClientId of the Azure Service principal created.
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # TenantId of the Azure Service principal created.
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # Azure subscriptionId
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    
    - name: Build Docker image
      run: |
        docker build -t dbclick-app .
        docker tag dbclick-app ${{ secrets.AZURE_CONTAINER_REGISTRY }}/dbclick-app:latest
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/dbclick-app:latest

    - name: Deploy to Azure App Service
      run: az webapp config container set --name dbclick-app --resource-group rg-dbclick --container-image-name ${{ secrets.AZURE_CONTAINER_REGISTRY }}/dbclick-app:latest
