name: Terraform Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'main.tf'
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup working directory
      run: |
        mkdir -p .terraform
        sudo chown -R $USER .terraform
        sudo chmod -R 755 .terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        # ClientId of the Azure Service principal created.
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # TenantId of the Azure Service principal created.
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # Azure subscriptionId
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Download Terraform Plan
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob download \
            --account-name tfstatedbclick \
            --container-name tfplan \
            --name terraform.tfplan \
            --file terraform.tfplan \
            --auth-mode login || true

    - name: Terraform Init
      run: terraform init -upgrade
      env:
        ARM_USE_OIDC: true
        ARM_USE_CLI: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Force Unlock State (if needed)
      uses: azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          az storage blob lease break \
            --account-name tfstatedbclick \
            --container-name tfstate \
            --blob-name terraform.tfstate \
            --auth-mode login || true

    - name: Terraform Plan
      run: |
        sudo chmod -R 777 .
        terraform plan -out=terraform.tfplan -lock-timeout=5m
      env:
        ARM_USE_OIDC: true
        ARM_USE_CLI: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_db_user: ${{ vars.DB_USER }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_PASSWORD }}
        TF_VAR_container_registry_name: ${{ vars.AZURE_CONTAINER_REGISTRY }}

    - name: Upload Terraform Plan
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload \
            --account-name tfstatedbclick \
            --container-name tfplan \
            --name terraform.tfplan \
            --file terraform.tfplan \
            --overwrite \
            --auth-mode login

    - name: Terraform Apply
      run: terraform apply -lock-timeout=20m terraform.tfplan -parallelism=1
      env:
        ARM_USE_OIDC: true
        ARM_USE_CLI: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_db_user: ${{ vars.DB_USER }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_client_password: ${{ secrets.AZURE_CLIENT_PASSWORD }}
        TF_VAR_container_registry_name: ${{ vars.AZURE_CONTAINER_REGISTRY }}
