name: Terraform Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'main.tf'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_DB_USER: ${{ vars.DB_USER }}
        TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
